# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 11:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volt', models.FloatField(blank=True, default=0, null=True)),
                ('level', models.FloatField(blank=True, default=0, null=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=250)),
                ('folder', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Site'),
        ),
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Files'),
        ),
    ]
