# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_site_site_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='site_id',
        ),
    ]
